from google_images_download import google_images_download

# dog_breeds = ['affenpinscher',
#  'afghan hound',
#  'african hunting dog',
#  'airedale',
#  'american staffordshire terrier',
#  'appenzeller',
#  'australian terrier',
#  'basenji',
#  'basset',
#  'beagle',
#  'bedlington terrier',
#  'bernese mountain dog',
#  'black-and-tan coonhound',
#  'blenheim spaniel',
#  'bloodhound',
#  'bluetick',
#  'border collie',
#  'border terrier',
#  'borzoi',
#  'boston bull',
#  'bouvier des flandres',
#  'boxer',
#  'brabancon griffon',
#  'briard',
#  'brittany spaniel',
#  'bull mastiff',
#  'cairn',
#  'cardigan',
#  'chesapeake bay retriever',
#  'chihuahua',
#  'chow',
#  'clumber',
#  'cocker spaniel',
#  'collie',
#  'curly-coated retriever',
#  'dandie dinmont',
#  'dhole',
#  'dingo',
#  'doberman',
#  'english foxhound',
#  'english setter',
#  'english springer',
#  'entlebucher',
#  'eskimo dog',
#  'flat-coated retriever',
#  'french bulldog',
#  'german shepherd',
#  'german short-haired pointer',
#  'giant schnauzer',
#  'golden retriever',
#  'gordon setter',
#  'great dane',
#  'great pyrenees',
#  'greater swiss mountain dog',
#  'groenendael',
#  'ibizan hound',
#  'irish setter',
#  'irish terrier',
#  'irish water spaniel',
#  'irish wolfhound',
#  'italian greyhound',
#  'japanese spaniel',
#  'keeshond',
#  'kelpie',
#  'kerry blue terrier',
#  'komondor',
#  'kuvasz',
#  'labrador retriever',
#  'lakeland terrier',
#  'leonberg',
#  'lhasa',
#  'malamute',
#  'malinois',
#  'maltese dog',
#  'mexican hairless',
#  'miniature pinscher',
#  'miniature poodle',
#  'miniature schnauzer',
#  'newfoundland',
#  'norfolk terrier',
#  'norwegian elkhound',
#  'norwich terrier',
#  'old english sheepdog',
#  'otterhound',
#  'papillon',
#  'pekinese',
#  'pembroke',
#  'pomeranian',
#  'pug',
#  'redbone',
#  'rhodesian ridgeback',
#  'rottweiler',
#  'saint bernard',
#  'saluki',
#  'samoyed',
#  'schipperke',
#  'scotch terrier',
#  'scottish deerhound',
#  'sealyham terrier',
#  'shetland sheepdog',
#  'shih-tzu',
#  'siberian husky',
#  'silky terrier',
#  'soft-coated wheaten terrier',
#  'staffordshire bullterrier',
#  'standard poodle',
#  'standard schnauzer',
#  'sussex spaniel',
#  'tibetan mastiff',
#  'tibetan terrier',
#  'toy poodle',
#  'toy terrier',
#  'vizsla',
#  'walker hound',
#  'weimaraner',
#  'welsh springer spaniel',
#  'west highland white terrier',
#  'whippet',
#  'wire-haired fox terrier',
#  'yorkshire terrier']

dog_breeds = ['boxer dog', 'welsh cardigan dog', 'lhasa dog']

home_dir = "/cs/casmip/israelwei/Computer_Vision/Project_CV/google_data/dog_breeds/"
chrome_driver = "/cs/casmip/israelwei/Computer_Vision/Project_CV/google_data/chromedriver"

response = google_images_download.googleimagesdownload()
for breed in dog_breeds:
	arguments = {"keywords": breed, "limit": 210, "output_directory": home_dir, "chromedriver": chrome_driver}
	response.download(arguments)

